writer:
	gcc writer.c -o writer
CROSS-COMPILE:
# ../arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu-aarch64-none-elf/bin/aarch
	aarch64-none-linux-gnu-gcc writer.c -o writer
clean:
	rm -f *.o writer
